/*******************************************************************************
 * Copyright (c) 2010 Robert "Unlogic" Olofsson (unlogic@unlogic.se).
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser Public License v3
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-3.0-standalone.html
 ******************************************************************************/
package se.unlogic.hierarchy.foregroundmodules.gallery.beans;

import java.lang.reflect.Field;
import java.sql.Timestamp;

import se.unlogic.hierarchy.core.beans.User;
import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.reflection.ReflectionUtils;
import se.unlogic.standardutils.string.StringUtils;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "gallery_image_comments")
@XMLElement
public class Comment extends GeneratedElementable {

	public static final Field IMAGE_RELATION = ReflectionUtils.getField(Comment.class, "image");

	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer commentID;

	@DAOManaged(columnName = "imageID")
	@ManyToOne(remoteKeyField = "imageID")
	@XMLElement
	private Image image;

	@DAOManaged
	@WebPopulate(maxLength = 65535, required = true)
	@XMLElement(cdata = true)
	private String message;

	@DAOManaged(dontUpdateIfNull=true)
	@XMLElement(childName = "poster")
	private User poster;

	@DAOManaged
	@XMLElement
	private Timestamp added;

	@DAOManaged(dontUpdateIfNull=true)
	@XMLElement(childName = "editor")
	private User editor;

	@DAOManaged
	@XMLElement
	private Timestamp updated;

	@Override
	public String toString() {

		return StringUtils.substring(this.message, 30, "...") + " (ID: " + this.commentID + ")";
	}

	public Integer getCommentID() {

		return commentID;
	}

	public void setCommentID(Integer commentID) {

		this.commentID = commentID;
	}

	public Image getImage() {

		return image;
	}

	public void setImage(Image image) {

		this.image = image;
	}

	public String getMessage() {

		return message;
	}

	public void setMessage(String message) {

		this.message = message;
	}

	public User getPoster() {

		return poster;
	}

	public void setPoster(User poster) {

		this.poster = poster;
	}

	public Timestamp getAdded() {

		return added;
	}

	public void setAdded(Timestamp added) {

		this.added = added;
	}

	public User getEditor() {

		return editor;
	}

	public void setEditor(User editor) {

		this.editor = editor;
	}

	public Timestamp getUpdated() {

		return updated;
	}

	public void setUpdated(Timestamp updated) {

		this.updated = updated;
	}
}
