/*******************************************************************************
 * Copyright (c) 2010 Robert "Unlogic" Olofsson (unlogic@unlogic.se).
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser Public License v3
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-3.0-standalone.html
 ******************************************************************************/
package se.unlogic.hierarchy.foregroundmodules.gallery.beans;

import java.lang.reflect.Field;
import java.sql.Blob;
import java.util.List;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.reflection.ReflectionUtils;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "gallery_images")
@XMLElement
public class Image extends GeneratedElementable{

	public static final Field SMALL_THUMB_FIELD = ReflectionUtils.getField(Image.class, "smallThumb");
	public static final Field MEDIUM_THUMB_FIELD = ReflectionUtils.getField(Image.class, "mediumThumb");
	public static final Field COMMENTS_RELATION = ReflectionUtils.getField(Image.class, "comments");
	public static final Field GALLERY_RELATION = ReflectionUtils.getField(Image.class, "gallery");

	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer imageID;

	@DAOManaged
	@XMLElement
	private String filename;

	@DAOManaged
	private Blob smallThumb;

	@DAOManaged
	private Blob mediumThumb;

	@DAOManaged
	@XMLElement
	private Long lastModified;

	@DAOManaged(columnName = "galleryID")
	@ManyToOne(remoteKeyField = "galleryID")
	@XMLElement
	private Gallery gallery;

	@DAOManaged
	@OneToMany
	@XMLElement
	private List<Comment> comments;

	public Integer getImageID() {

		return imageID;
	}

	public void setImageID(Integer imageID) {

		this.imageID = imageID;
	}

	public String getFilename() {

		return filename;
	}

	public void setFilename(String filename) {

		this.filename = filename;
	}

	public Blob getSmallThumb() {

		return smallThumb;
	}

	public void setSmallThumb(Blob smallThumb) {

		this.smallThumb = smallThumb;
	}

	public Blob getMediumThumb() {

		return mediumThumb;
	}

	public void setMediumThumb(Blob mediumThumb) {

		this.mediumThumb = mediumThumb;
	}

	public Gallery getGallery() {

		return gallery;
	}

	public void setGallery(Gallery gallery) {

		this.gallery = gallery;
	}

	public List<Comment> getComments() {

		return comments;
	}

	public void setComments(List<Comment> comments) {

		this.comments = comments;
	}

	@Override
	public String toString() {

		return this.filename + "(ID: " + imageID + ")";
	}

	public Long getLastModified() {

		return lastModified;
	}

	public void setLastModified(Long generated) {

		this.lastModified = generated;
	}
}
