package demo.oeplatform.org.queries.CalculationBasisQuery3;

import java.io.Serializable;
import java.lang.reflect.Field;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.reflection.ReflectionUtils;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "calculationbasis_query_instance_values")
@XMLElement
public class CalculationBasisValue extends GeneratedElementable implements Serializable {

	private static final long serialVersionUID = 6354162344651352603L;

	public static final Field TEXT_FIELD_RELATION = ReflectionUtils.getField(CalculationBasisValue.class, "calculationBasis");

	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer calculationBasisValueID;

	@DAOManaged(columnName = "queryInstanceID")
	@ManyToOne
	private CalculationBasisQueryInstance instance;

	@DAOManaged(columnName = "calculationBasisID")
	@ManyToOne
	@XMLElement
	private CalculationBasis calculationBasis;

	@DAOManaged
	@XMLElement
	private String value;

	public CalculationBasisValue() {};

	public CalculationBasisValue(CalculationBasis calculationBasis, String value) {

		super();
		this.calculationBasis = calculationBasis;
		this.value = value;
	}

	public Integer getCalculationBasisValueID() {

		return calculationBasisValueID;
	}

	public void setCalculationBasisValueID(Integer calculationBasisValueID) {

		this.calculationBasisValueID = calculationBasisValueID;
	}

	public CalculationBasisQueryInstance getInstance() {

		return instance;
	}

	public void setInstance(CalculationBasisQueryInstance instance) {

		this.instance = instance;
	}

	public CalculationBasis getCalculationBasis() {

		return calculationBasis;
	}

	public void setCalculationBasis(CalculationBasis calculationBasis) {

		this.calculationBasis = calculationBasis;
	}

	public String getValue() {

		return value;
	}

	public void setValue(String value) {

		this.value = value;
	}
}
